name: recipe_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  get: ^4.7.2
  pretty_dio_logger: ^1.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/
